<?php

namespace AppBundle\Repository;



/**
 * ChildGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildGroupRepository extends \Doctrine\ORM\EntityRepository
{

}
