<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserDocuments(User $user)
    {
        $query = $this->createQueryBuilder('d');

        $query->orWhere('d.user = ' . $user->getId());

        foreach ($user->getSponsorGroups() as $group) {
            $query->orWhere('d.group = ' . $group->getId());
        }

        return $query
            ->orderBy('d.order', 'DESC')
            ->getQuery()
            ->getResult()
        ;
    }
}
