<?php

namespace AppBundle\Repository;

/**
 * FollowUpExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowUpExportRepository extends \Doctrine\ORM\EntityRepository
{
}
