<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LetterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LetterRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLetters($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('l')
            ->orderBy('l.creationDate', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1)*$nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }
}
