<?php

namespace AppBundle\Repository;
use AppBundle\Entity\SponsorGroup;
use AppBundle\Entity\User;

/**
 * MessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserMessages(User $user)
    {
        $query = $this->createQueryBuilder('m')
            ->leftjoin('m.user', 'u', 'WITH')
            ->where('u.id = :userID')
            ->setParameter('userID', $user->getId())
            ->leftjoin('m.group', 'g', 'WITH')
        ;

        foreach ($user->getSponsorGroups() as $group) {
            $query
                ->orWhere('g.id = '.$group->getId())
            ;
        }

        $query
            ->orderBy('m.creationDate', 'ASC')
            ->setFirstResult(0)
            ->setMaxResults(30)
        ;

        return $query->getQuery()->getResult();
    }
}
