<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * RecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecordRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRecords($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('r')
            ->orderBy('r.datetime', 'DESC')
            ->getQuery()
        ;

        $query
            // On définit l'annonce à partir de laquelle commencer la liste
            ->setFirstResult(($page-1)*$nbPerPage)
            // Ainsi que le nombre d'annonce à afficher sur une page
            ->setMaxResults($nbPerPage)
        ;

        // On retourne l'objet Paginator correspondant à la requête construite
        return new Paginator($query, true);
    }

    public function getRecordsOlderThan($date)
    {
        $qb = $this->createQueryBuilder('r');

        $qb->where($qb->expr()->orX(
                $qb->expr()->lte('r.datetime', ':paramDate')
            ))
            ->setParameter('paramDate', $date, \Doctrine\DBAL\Types\Type::DATETIME)
        ;

        return $qb->getQuery()->getResult();
    }
}
