<?php

namespace AppBundle\Repository;

/**
 * SponsorGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorGroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function getGroupsList()
    {
        return $this->createQueryBuilder('s')
            ->orderBy('s.name', 'ASC')
            ;
    }
}
