<?php

namespace AppBundle\Repository;

/**
 * RequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorshipRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
