imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

    globals:
        file_base_url: '%file_base_url%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# fos_user Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    filters:
      cssrewrite: ~

# VichUploader Configuration
vich_uploader:
    db_driver: orm

    mappings:
        photos_child_profile:
            uri_prefix: uploads/photos/child/profile
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/child/profile'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname

        photos_child_library:
            uri_prefix: uploads/photos/child/library
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/child/library'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname

        sponsor_file:
            uri_prefix: uploads/sponsor/files
            upload_destination: '%kernel.root_dir%/../web/uploads/sponsor/files'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname

        post_image:
            uri_prefix: uploads/photos/posts
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/posts'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname

        letter_module_photo:
            uri_prefix: uploads/photos/letters
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/letters'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname

        gallery_photo:
            uri_prefix: uploads/photos/gallery
            upload_destination: '%kernel.root_dir%/../web/uploads/photos/gallery'
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            namer: vich_uploader.namer_origname


# Stof Configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true