# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

  send.account_data:
              class: AppBundle\Utils\sendAccountData
              arguments:
                  - "@mailer"
                  - "@templating"
                  - "%mailer_user%"

  app.form.create_user:
      class: AppBundle\Form\CreateUserType
      arguments: ['@security.token_storage']
      tags:
          - { name: form.type }


  authentication.handler.login_success_handler:
      class:  AppBundle\Security\LoginSuccessHandler
      arguments:  ['@router', '@security.authorization_checker']